### ISSUE TITLE
Error when compiling

### ISSUE THREAD

**Issue by Yamato1994** [can1357/simple_aoe3_maphack#2]
When I try to compile your code I get the following errors:

12	7	C:\Users\HP\Desktop\Main.cpp	[Error] expected nested-name-specifier before 'pointer_t'
14	7	C:\Users\HP\Desktop\Main.cpp	[Warning] user-defined literals only available with -std=c++11 or -std=gnu++11
14	7	C:\Users\HP\Desktop\Main.cpp	[Warning] user-defined literals only available with -std=c++11 or -std=gnu++11
15	6	C:\Users\HP\Desktop\Main.cpp	[Error] 'pointer_t' was not declared in this scope
15	23	C:\Users\HP\Desktop\Main.cpp	[Error] template argument 1 is invalid
15	89	C:\Users\HP\Desktop\Main.cpp	[Error] invalid type in declaration before ';' token
16	1	C:\Users\HP\Desktop\Main.cpp	[Error] 'pointer_t' does not name a type
17	6	C:\Users\HP\Desktop\Main.cpp	[Error] 'pointer_t' was not declared in this scope
17	23	C:\Users\HP\Desktop\Main.cpp	[Error] template argument 1 is invalid
17	53	C:\Users\HP\Desktop\Main.cpp	[Error] invalid type in declaration before ';' token
30	1	C:\Users\HP\Desktop\Main.cpp	[Error] 'pointer_t' does not name a type
C:\Users\HP\Desktop\Main.cpp	In function 'bool PatchVisibilityRequirement(HANDLE, int)':
49	2	C:\Users\HP\Desktop\Main.cpp	[Error] 'pointer_t' was not declared in this scope
58	8	C:\Users\HP\Desktop\Main.cpp	[Error] 'pBranch' was not declared in this scope
70	32	C:\Users\HP\Desktop\Main.cpp	[Error] 'pBranch' was not declared in this scope
C:\Users\HP\Desktop\Main.cpp	In function 'int main(int, char**)':
82	8	C:\Users\HP\Desktop\Main.cpp	[Error] invalid conversion from 'const char*' to 'int' [-fpermissive]
82	20	C:\Users\HP\Desktop\Main.cpp	[Error] expected ';' before '_pid'
84	8	C:\Users\HP\Desktop\Main.cpp	[Error] invalid conversion from 'const char*' to 'int' [-fpermissive]
84	21	C:\Users\HP\Desktop\Main.cpp	[Error] expected ';' before '_pid'
86	8	C:\Users\HP\Desktop\Main.cpp	[Error] invalid conversion from 'const char*' to 'int' [-fpermissive]
86	21	C:\Users\HP\Desktop\Main.cpp	[Error] expected ';' before '_pid'
C:\Users\HP\Desktop\Main.cpp	At global scope:
128	7	C:\Users\HP\Desktop\Main.cpp	[Warning] user-defined literals only available with -std=c++11 or -std=gnu++11
128	7	C:\Users\HP\Desktop\Main.cpp	[Warning] user-defined literals only available with -std=c++11 or -std=gnu++11
C:\Users\HP\Desktop\Main.cpp	In function 'DWORD operator""_pid(const char*, size_t)':
135	71	C:\Users\HP\Desktop\Main.cpp	[Warning] passing NULL to non-pointer argument 2 of 'void* CreateToolhelp32Snapshot(DWORD, DWORD)' [-Wconversion-null]
C:\Users\HP\Desktop\Main.cpp	At global scope:
153	6	C:\Users\HP\Desktop\Main.cpp	[Error] 'pointer_t' was not declared in this scope
153	23	C:\Users\HP\Desktop\Main.cpp	[Error] template argument 1 is invalid
C:\Users\HP\Desktop\Main.cpp	In function 'int GetModuleBaseAndSize(DWORD, const char*)':
156	2	C:\Users\HP\Desktop\Main.cpp	[Error] 'pointer_t' was not declared in this scope
168	35	C:\Users\HP\Desktop\Main.cpp	[Error] type/value mismatch at argument 1 in template parameter list for 'template<class _T1, class _T2> struct std::pair'
168	35	C:\Users\HP\Desktop\Main.cpp	[Error] expected a type, got 'pointer_t'
168	49	C:\Users\HP\Desktop\Main.cpp	[Error] expected ')' before 'ModuleEntry32'
174	31	C:\Users\HP\Desktop\Main.cpp	[Error] type/value mismatch at argument 1 in template parameter list for 'template<class _T1, class _T2> struct std::pair'
174	31	C:\Users\HP\Desktop\Main.cpp	[Error] expected a type, got 'pointer_t'
C:\Users\HP\Desktop\Main.cpp	At global scope:
176	1	C:\Users\HP\Desktop\Main.cpp	[Error] 'pointer_t' does not name a type
216	6	C:\Users\HP\Desktop\Main.cpp	[Error] 'pointer_t' was not declared in this scope
216	23	C:\Users\HP\Desktop\Main.cpp	[Error] template argument 1 is invalid
C:\Users\HP\Desktop\Main.cpp	In function 'int GetAge3ModuleBase(int)':
218	7	C:\Users\HP\Desktop\Main.cpp	[Error] 'pointer_t' was not declared in this scope
218	24	C:\Users\HP\Desktop\Main.cpp	[Error] template argument 1 is invalid
218	28	C:\Users\HP\Desktop\Main.cpp	[Error] invalid type in declaration before '=' token
219	24	C:\Users\HP\Desktop\Main.cpp	[Error] type/value mismatch at argument 1 in template parameter list for 'template<class _T1, class _T2> struct std::pair'
219	24	C:\Users\HP\Desktop\Main.cpp	[Error] expected a type, got 'pointer_t'
219	28	C:\Users\HP\Desktop\Main.cpp	[Error] invalid type in declaration before '=' token
220	24	C:\Users\HP\Desktop\Main.cpp	[Error] type/value mismatch at argument 1 in template parameter list for 'template<class _T1, class _T2> struct std::pair'
220	24	C:\Users\HP\Desktop\Main.cpp	[Error] expected a type, got 'pointer_t'
220	28	C:\Users\HP\Desktop\Main.cpp	[Error] invalid type in declaration before '=' token
221	12	C:\Users\HP\Desktop\Main.cpp	[Error] request for member 'second' in 'x', which is of non-class type 'int'
222	5	C:\Users\HP\Desktop\Main.cpp	[Error] request for member 'second' in 'y', which is of non-class type 'int'
223	5	C:\Users\HP\Desktop\Main.cpp	[Error] request for member 'second' in 'v', which is of non-class type 'int'
223	40	C:\Users\HP\Desktop\Main.cpp	[Error] type/value mismatch at argument 1 in template parameter list for 'template<class _T1, class _T2> struct std::pair'
223	40	C:\Users\HP\Desktop\Main.cpp	[Error] expected a type, got 'pointer_t'

I tried to do it with Visual Studio and with Dev C++ and i receive the same errors. Could you help me please? 
Thank you.

**Comment by can1357** [comment]
Visual Studio 2015?

**Comment by Yamato1994** [comment]
Visual Studio Community 2017

**Comment by can1357** [comment]
compiles fine for me.
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

**Comment by Yamato1994** [comment]
When i open de .cpp on Visual Studio 2015 i didnt have the option to compile or run, i only have "associate" to another process. How can i compile and run it?

**Comment by Yamato1994** [comment]
I have solved the problem. Thank you
