### ISSUE TITLE
Couldn't find visibility branch

### ISSUE THREAD

**Issue by Anjato** [can1357/simple_aoe3_maphack#3]
Not sure how to fix it but here's a screenshot of the error. Checked to see if the AoB is updated and it is and so are the bytes in that section so I'm not quite sure what's wrong with it.

https://gyazo.com/0b1bcbd3a81549b97ced267281933f32

https://gyazo.com/a93b82f31686c40d1a6e1f33e14d8e4b

**Comment by can1357** [comment]
Can you make sure OpenProcess returns a valid handle by printing the handle and the return value of GetLastError()?

Sounds like it is simply a permission problem to me (Admin vs regular user).

**Comment by Anjato** [comment]
You were right about admin privileges. Got it working. Thanks! It's a little buggy it seems but it does work as well as it needs to :)
